Default: &defaults
  user: example
  password: example
  host: localhost
  port: 5432
  database: example
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: example_test
  <<: *defaults

Staging:
  database: example_staging
  poolsize: 100
  <<: *defaults

Production:
  database: example_production
  poolsize: 100
  <<: *defaults
